services:

  {{project_name}}:
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-server

  consul-server:
    image: consul
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - volume-consul:/consul/data

networks:
  default:
    driver: bridge

volumes:
  volume-consul:
